#!/usr/bin/env python3
"""Generate MoonBit compliance tests from jmespath.py's JSON test suite.

Reads upstream/jmespath.py/tests/compliance/*.json (and tests/legacy/*.json,
which upstream's test_compliance.py also walks) and writes one
jmespath/compliance_<name>_test.mbt per file.  Each generated file embeds the
*raw* fixture text with `#|` multiline string literals (so numbers keep their
original spelling), parses it at test time with `@jmespath.loads` (a port of
Python's json.loads that keeps the int/float distinction) and runs every case
through `run_compliance_case` (see compliance_helpers_test.mbt).

Usage (from anywhere):  python3 jmespath/scripts/gen_compliance.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
ROOT = os.path.dirname(PKG)
TESTS = os.path.join(ROOT, "upstream", "jmespath.py", "tests")
SOURCES = [("compliance", ""), ("legacy", "legacy_")]


def mbt_string(s):
    """A MoonBit string literal for `s`."""
    out = ['"']
    for ch in s:
        code = ord(ch)
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            out.append('\\r')
        elif ch == '\t':
            out.append('\\t')
        elif code < 0x20 or code == 0x7f:
            out.append('\\u{%x}' % code)
        else:
            out.append(ch)
    out.append('"')
    return ''.join(out)


def generate(path, prefix):
    name = prefix + os.path.splitext(os.path.basename(path))[0]
    with open(path, encoding="utf-8") as f:
        raw = f.read()
    suite = json.loads(raw)
    var = "compliance_%s_suite" % name
    lines = [
        "// Code generated by scripts/gen_compliance.py from",
        "// upstream/jmespath.py/tests/%s. DO NOT EDIT." % os.path.relpath(
            path, TESTS),
        "",
        "///|",
        "let %s : Json = {" % var,
        "  let raw =",
    ]
    for line in raw.rstrip("\n").split("\n"):
        lines.append("    #|" + line)
    lines.append("  try! @jmespath.loads(raw)")
    lines.append("}")
    count = 0
    for gi, group in enumerate(suite):
        for ci, case in enumerate(group["cases"]):
            title = "compliance/%s/%d/%d: %s" % (name, gi, ci,
                                                case["expression"])
            lines += [
                "",
                "///|",
                "test %s {" % mbt_string(title),
                "  run_compliance_case(%s, %d, %d)" % (var, gi, ci),
                "}",
            ]
            count += 1
    out = os.path.join(PKG, "compliance_%s_test.mbt" % name)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return out, count


def main():
    total = 0
    for subdir, prefix in SOURCES:
        directory = os.path.join(TESTS, subdir)
        for filename in sorted(os.listdir(directory)):
            if filename.endswith(".json"):
                out, count = generate(os.path.join(directory, filename),
                                      prefix)
                total += count
                print("%s: %d cases" % (os.path.relpath(out, ROOT), count))
    print("total: %d cases" % total)


if __name__ == "__main__":
    sys.exit(main())
