#!/usr/bin/env python3
"""
Generate MoonBit black-box tests from the shared JSON referencing test suite
(https://github.com/python-jsonschema/referencing-suite), mirroring upstream's
referencing/tests/test_referencing_suite.py.

Usage (from the workspace root):

    python3 referencing/scripts/gen_suite.py [path/to/referencing-suite/tests]

Writes referencing/suite_<draft>_test.mbt, one `test` per suite file. The JSON
is embedded verbatim in `#|` multiline strings and parsed with `@json.parse`
at test time; `suite_runner_test.mbt` holds the runner.
"""
from pathlib import Path
import json
import sys

HERE = Path(__file__).resolve().parent
PACKAGE = HERE.parent
DEFAULT_SUITE = PACKAGE.parent / "upstream" / "referencing-suite" / "tests"


def mbt_string_literal(s):
    return json.dumps(s, ensure_ascii=False).replace("\\/", "/")


def main():
    suite = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SUITE
    dialect_ids = json.loads((suite / "specifications.json").read_text())
    for old in PACKAGE.glob("suite_json_schema_*_test.mbt"):
        old.unlink()
    total = 0
    for draft_dir in sorted(p for p in suite.iterdir() if p.is_dir()):
        dialect_id = dialect_ids[draft_dir.name]
        # upstream: SUITE.glob("*/**/*.json")
        paths = sorted(draft_dir.glob("**/*.json"))
        lines = [
            "// Generated by referencing/scripts/gen_suite.py from the referencing",
            f"// suite ({draft_dir.name}). DO NOT EDIT.",
            "",
        ]
        for path in paths:
            rel = path.relative_to(draft_dir).with_suffix("")
            name = f"{draft_dir.name}/{rel.as_posix()}"
            # upstream xfails these: "APIs need to change for proper URL support."
            xfail = "normalization" in path.stem
            text = path.read_text()
            json.loads(text)  # sanity check
            lines.append("///|")
            lines.append(f"test {mbt_string_literal('suite: ' + name)} {{")
            lines.append("  run_suite_file(")
            lines.append(f"    {mbt_string_literal(name)},")
            lines.append(f"    {mbt_string_literal(dialect_id)},")
            lines.append(f"    xfail={'true' if xfail else 'false'},")
            lines.append("    (")
            for line in text.rstrip("\n").split("\n"):
                lines.append(f"      #|{line}".rstrip() if line.strip() == "" else f"      #|{line}")
            lines.append("    ),")
            lines.append("  )")
            lines.append("}")
            lines.append("")
            total += 1
        out = PACKAGE / f"suite_{draft_dir.name.replace('-', '_')}_test.mbt"
        out.write_text("\n".join(lines))
        print(f"wrote {out.name} ({len(paths)} files)")
    print(f"total: {total} suite files")


main()
