#!/usr/bin/env python3
"""
Generate referencing/urllib/urllib_python_test.mbt: a table of cases whose
expected outputs come from CPython's own `urllib.parse`.

Usage: python3 referencing/scripts/gen_urllib_tests.py
"""
from pathlib import Path
from urllib.parse import unquote, urldefrag, urljoin, urlsplit, urlparse
import sys

OUT = Path(__file__).resolve().parent.parent / "urllib" / "urllib_python_test.mbt"

BASES = [
    "",
    "http://example.com",
    "http://example.com/",
    "http://example.com/a/b/c",
    "http://example.com/a/b/c/",
    "http://a/b/c/d;p?q",
    "https://json-schema.org/draft/2020-12/schema",
    "http://example.com/foo#",
    "http://example.com/foo?x=1#frag",
    "urn:example:foo",
    "urn:uuid:deadbeef-1234-ffff-ffff-4321feebdaed",
    "tag:example.com,2023:schema",
    "file:///tmp/schemas/root.json",
    "mailto:someone@example.com",
    "ftp://ftp.example.com/pub/file",
    "//example.com/path",
    "relative/path",
    "/absolute/path",
    "http://[::1]:8080/a/",
    "http://user:pw@example.com:80/a/../b",
    "http://example.com/%7Efoo/bar%20baz",
    "HTTP://Example.COM/A",
    "http://example.com/a/./b/../c",
    "svn+ssh://host/repo/trunk",
    "itms-services://example/a/b",
]

REFS = [
    "",
    "#",
    "#foo",
    "#/definitions/a",
    "#/$defs/a%25b",
    "g",
    "./g",
    "g/",
    "/g",
    "//g",
    "?y",
    "g?y",
    "g#s",
    "g?y#s",
    ";x",
    "g;x",
    "g;x?y#s",
    ".",
    "./",
    "..",
    "../",
    "../g",
    "../..",
    "../../",
    "../../g",
    "../../../g",
    "../../../../g",
    "/./g",
    "/../g",
    "g.",
    ".g",
    "g..",
    "..g",
    "./../g",
    "./g/.",
    "g/./h",
    "g/../h",
    "g;x=1/./y",
    "g;x=1/../y",
    "http:g",
    "http:",
    "urn:example:bar",
    "urn:example:foo#bar",
    "tag:example.com,2023:other",
    "https://other.example/x",
    "foo/bar/",
    "bar",
    "child/",
    "grandchild",
    "a%20b",
    "  leading-space",
    "with\ttab",
    "mailto:x@y",
    "file:other.json",
    "nested/../../up",
    "a//b",
    "//",
    "///x",
]

SPLITS = [
    "http://example.com/a/b?c=d#e",
    "HTTP://EXAMPLE.com",
    "urn:example:foo#bar",
    "tag:example.com,2023:x",
    "mailto:a@b.c",
    "//netloc/path?q#f",
    "path;params?q#f",
    "http://a/b;c/d;e?f#g",
    "1http://x",
    "a+b-c.d:rest",
    "a_b:rest",
    ":nope",
    "http://[::1]/",
    "http://[::ffff:1.2.3.4]:80/",
    "http://[fe80::1%25eth0]/",
    "http://[v1.fe]/",
    "  \x00http://example.com/  ",
    "ht\ttp://exa\nmple.com/\r",
    "#only-fragment",
    "?only-query",
    "",
    "file:///etc/passwd",
    "http://user@[::1]:99/x",
    "http://example.com:80",
]

BAD_SPLITS = [
    "http://[::1/",
    "http://::1]/",
    "http://[1.2.3.4]/",
    "http://[v.x]/",
    "http://[vz.x]/",
    "http://[::1]x/",
    "http://x[::1]/",
    "http://[::1::2]/",
    "http://[12345::]/",
    "http://[hello]/",
    "http://[a@b]@x/",
]

DEFRAGS = [
    "http://example.com/a#b",
    "http://example.com/a#",
    "http://example.com/a",
    "urn:example:foo#bar",
    "urn:example:foo#",
    "#",
    "#foo",
    "",
    "http://a/b;p?q#f",
    "tag:x#/a/b",
    "http://example.com/?#",
    "//x/y#z",
]

UNQUOTES = [
    "",
    "abc",
    "abc%20def",
    "%7e%7E",
    "%",
    "%2",
    "%zz",
    "%%41",
    "%E2%82%AC",
    "%E2%82",
    "%E2%82%",
    "%FF",
    "%C3%A9t%C3%A9",
    "%C3",
    "%ED%A0%80",
    "%F0%9F%98%80",
    "%F0%9F%98",
    "café%20bar",
    "é%C3%A9",
    "%C3é%A9",
    "~0~1%7E0",
    "a%2Fb",
    "/definitions/foo%22bar",
    "%25",
    "%2525",
    "%80%80",
    "%C0%AF",
    "%F4%90%80%80",
]


def mbt_str(s):
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F:
            out.append("\\u{%x}" % o)
        elif ch == "{" and False:
            out.append(ch)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def main():
    lines = [
        "// Generated by referencing/scripts/gen_urllib_tests.py from CPython "
        + sys.version.split()[0]
        + "'s urllib.parse. DO NOT EDIT.",
        "",
    ]

    lines += ["///|", 'test "urljoin matches CPython" {', "  let cases : Array[(String, String, String)] = ["]
    n = 0
    for base in BASES:
        for ref in REFS:
            lines.append(f"    ({mbt_str(base)}, {mbt_str(ref)}, {mbt_str(urljoin(base, ref))}),")
            n += 1
    lines += [
        "  ]",
        "  for case in cases {",
        "    let (base, url, expected) = case",
        "    let got = @urllib.urljoin(base, url)",
        '    assert_eq(got, expected, msg="urljoin(\\{base}, \\{url})")',
        "  }",
        "}",
        "",
    ]

    lines += ["///|", 'test "urlsplit and urlparse match CPython" {']
    lines += ["  let cases : Array[(String, Array[String], Array[String])] = ["]
    for url in SPLITS:
        s = urlsplit(url)
        p = urlparse(url)
        lines.append(
            f"    ({mbt_str(url)}, [{', '.join(mbt_str(x) for x in s)}], "
            f"[{', '.join(mbt_str(x) for x in p)}]),"
        )
    lines += [
        "  ]",
        "  for case in cases {",
        "    let (url, s, p) = case",
        "    let got = @urllib.urlsplit(url)",
        "    assert_eq([got.scheme, got.netloc, got.path, got.query, got.fragment], s)",
        "    let got = @urllib.urlparse(url)",
        "    assert_eq(",
        "      [got.scheme, got.netloc, got.path, got.params, got.query, got.fragment],",
        "      p,",
        "    )",
        "    assert_eq(@urllib.urlsplit(url).geturl(), " "@urllib.urlunsplit(s[0], s[1], s[2], s[3], s[4]))",
        "  }",
        "}",
        "",
    ]

    lines += ["///|", 'test "urlsplit raises ValueError like CPython" {']
    lines += ["  let cases : Array[(String, String)] = ["]
    for url in BAD_SPLITS:
        try:
            urlsplit(url)
        except ValueError as e:
            lines.append(f"    ({mbt_str(url)}, {mbt_str(str(e))}),")
        else:
            raise SystemExit(f"expected {url!r} to fail")
    lines += [
        "  ]",
        "  for case in cases {",
        "    let (url, message) = case",
        "    try @urllib.urlsplit(url) catch {",
        "      @urllib.ValueError(got) => assert_eq(got, message)",
        "    } noraise {",
        '      _ => fail("expected \\{url} to fail")',
        "    }",
        "  }",
        "}",
        "",
    ]

    lines += ["///|", 'test "urldefrag matches CPython" {']
    lines += ["  let cases : Array[(String, String, String)] = ["]
    for url in DEFRAGS:
        d = urldefrag(url)
        lines.append(f"    ({mbt_str(url)}, {mbt_str(d.url)}, {mbt_str(d.fragment)}),")
    lines += [
        "  ]",
        "  for case in cases {",
        "    let (url, defragged, fragment) = case",
        "    let got = @urllib.urldefrag(url)",
        "    assert_eq(got.url, defragged)",
        "    assert_eq(got.fragment, fragment)",
        "  }",
        "}",
        "",
    ]

    lines += ["///|", 'test "unquote matches CPython" {']
    lines += ["  let cases : Array[(String, String)] = ["]
    for s in UNQUOTES:
        lines.append(f"    ({mbt_str(s)}, {mbt_str(unquote(s))}),")
    lines += [
        "  ]",
        "  for case in cases {",
        "    let (input, expected) = case",
        "    assert_eq(@urllib.unquote(input), expected, msg=\"unquote(\\{input})\")",
        "  }",
        "}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({n} urljoin cases)")


main()
