#!/usr/bin/env python3
"""
Generate internal/unicodedata/tables.mbt.

The tables mirror what CPython's ``unicodedata`` / ``str`` predicates and the
``idna`` package (``idna.idnadata``) report, so that the MoonBit port of
python-jsonschema's format checkers behaves like upstream running with all of
its ``format`` extras installed.

Usage (needs the ``idna`` package importable):

    python3 jsonschema/scripts/gen_unicodedata.py
"""
import os
import sys
import unicodedata

import idna
import idna.idnadata as idnadata

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "internal", "unicodedata", "tables.mbt")

MAX = 0x110000


def ranges_of(pred):
    out = []
    start = None
    for cp in range(MAX):
        ok = pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def runs_of(value_of):
    """Return (starts, values) where each run [starts[i], starts[i+1]) has a
    constant value."""
    starts, values = [], []
    prev = object()
    for cp in range(MAX):
        v = value_of(cp)
        if v != prev:
            starts.append(cp)
            values.append(v)
            prev = v
    return starts, values


def fmt_ints(name, ints, doc):
    lines = [f"///|\n/// {doc}\nlet {name} : FixedArray[Int] = ["]
    row = []
    for i in ints:
        row.append(str(i))
        if len(row) == 12:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("]\n")
    return "\n".join(lines)


def flat(ranges):
    out = []
    for s, e in ranges:
        out += [s, e]
    return out


def is_surrogate(cp):
    return 0xD800 <= cp <= 0xDFFF


def main():
    chunks = [
        "// Code generated by jsonschema/scripts/gen_unicodedata.py. DO NOT EDIT.\n"
        f"// Python unicodedata {unicodedata.unidata_version}; idna {idna.__version__}"
        f" (idnadata {idnadata.__version__}).\n",
    ]

    def boolprop(name, pred, doc):
        chunks.append(fmt_ints(name, flat(ranges_of(pred)), doc))

    boolprop("decimal_ranges", lambda cp: chr(cp).isdecimal(),
             "Code points for which `str.isdecimal()` holds (`\\d` in `re`).")
    boolprop("alnum_ranges", lambda cp: chr(cp).isalnum(),
             "Code points for which `str.isalnum()` holds (`\\w` in `re`, minus `_`).")
    boolprop("alpha_ranges", lambda cp: chr(cp).isalpha(),
             "Code points for which `str.isalpha()` holds.")
    boolprop("space_ranges", lambda cp: chr(cp).isspace(),
             "Code points for which `str.isspace()` holds (`\\s` in `re`).")
    boolprop("printable_ranges", lambda cp: chr(cp).isprintable(),
             "Code points for which `str.isprintable()` holds (used by `repr`).")
    boolprop("mark_ranges",
             lambda cp: unicodedata.category(chr(cp)).startswith("M"),
             "Code points whose general category is `M*`.")
    boolprop("unnamed_ranges",
             lambda cp: unicodedata.name(chr(cp), None) is None,
             "Code points for which `unicodedata.name` raises `ValueError`.")

    starts, values = runs_of(lambda cp: unicodedata.combining(chr(cp)))
    chunks.append(fmt_ints("ccc_starts", starts, "Run starts of canonical combining classes."))
    chunks.append(fmt_ints("ccc_values", values, "Canonical combining class for each run."))

    bidi_names = sorted({unicodedata.bidirectional(chr(cp)) for cp in range(MAX)})
    idx = {n: i for i, n in enumerate(bidi_names)}
    starts, values = runs_of(lambda cp: idx[unicodedata.bidirectional(chr(cp))])
    chunks.append(
        "///|\n/// Names of bidirectional classes (`\"\"` means unknown).\n"
        "let bidi_names : FixedArray[String] = ["
        + ", ".join(f'"{n}"' for n in bidi_names) + "]\n"
    )
    chunks.append(fmt_ints("bidi_starts", starts, "Run starts of bidirectional classes."))
    chunks.append(fmt_ints("bidi_values", values, "Index into `bidi_names` for each run."))

    # Canonical decompositions (non-Hangul).
    dec_cps, dec_offsets, dec_data = [], [0], []
    comp = []
    for cp in range(MAX):
        if is_surrogate(cp):
            continue
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        parts = [int(x, 16) for x in d.split()]
        dec_cps.append(cp)
        dec_data += parts
        dec_offsets.append(len(dec_data))
        if len(parts) == 2 and unicodedata.normalize("NFC", chr(cp)) == chr(cp):
            comp.append((parts[0], parts[1], cp))
    comp.sort()
    chunks.append(fmt_ints("decomp_cps", dec_cps, "Code points with a canonical decomposition."))
    chunks.append(fmt_ints("decomp_offsets", dec_offsets, "Offsets into `decomp_data`."))
    chunks.append(fmt_ints("decomp_data", dec_data, "Flattened canonical decompositions."))
    flat_comp = []
    for a, b, c in comp:
        flat_comp += [a, b, c]
    chunks.append(fmt_ints("compose_triples", flat_comp,
                           "Primary composites as sorted `(first, second, composite)` triples."))

    # Case-insensitive equivalence classes of `re` (str patterns, Unicode).
    import re
    import re._casefix as casefix
    parent = {}

    def find(x):
        while parent.get(x, x) != x:
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[max(ra, rb)] = min(ra, rb)

    for cp in range(MAX):
        if is_surrogate(cp):
            continue
        c = chr(cp)
        cands = set()
        for v in (c.lower(), c.upper(), c.title(), c.swapcase()):
            if len(v) == 1:
                cands.add(ord(v))
        low = c.lower()
        for v in (casefix._EXTRA_CASES.get(ord(low), ()) if len(low) == 1 else ()):
            cands.add(v)
        pat = re.compile("(?i)" + re.escape(c))
        for x in cands:
            if x != cp and pat.fullmatch(chr(x)):
                union(cp, x)
    groups = {}
    for cp in list(parent):
        groups.setdefault(find(cp), set()).add(cp)
    flat_pairs = []
    for root in sorted(groups):
        members = sorted(groups[root] | {root})
        for m in members:
            flat_pairs += [m, root]
    flat_pairs_sorted = []
    for m, root in sorted(zip(flat_pairs[0::2], flat_pairs[1::2])):
        flat_pairs_sorted += [m, root]
    chunks.append(fmt_ints("case_classes", flat_pairs_sorted,
                           "`(code point, class representative)` pairs, sorted by code point, of `re`'s case-insensitive equivalence classes (code points absent are alone)."))

    def intranges(name, r, doc):
        out = []
        for v in r:
            out += [v >> 32, (v & 0xFFFFFFFF) - 1]
        chunks.append(fmt_ints(name, out, doc))

    for cls in ["PVALID", "CONTEXTJ", "CONTEXTO"]:
        intranges(f"idna_{cls.lower()}_ranges", idnadata.codepoint_classes[cls],
                  f"`idna.idnadata.codepoint_classes[{cls!r}]` as inclusive ranges.")
    for script in ["Greek", "Han", "Hebrew", "Hiragana", "Katakana"]:
        intranges(f"idna_script_{script.lower()}_ranges", idnadata.scripts[script],
                  f"`idna.idnadata.scripts[{script!r}]` as inclusive ranges.")
    for jt in ["C", "D", "L", "R", "T"]:
        intranges(f"idna_joining_{jt.lower()}_ranges", idnadata.joining_types[jt],
                  f"`idna.idnadata.joining_types[{jt!r}]` as inclusive ranges.")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(chunks))
    print(f"wrote {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
