#!/usr/bin/env python3
"""
Generate MoonBit tests from the official JSON-Schema-Test-Suite.

For every (test class, suite file) group run by upstream's
``jsonschema/tests/test_jsonschema_test_suite.py`` (see ``suite_config.py``)
this writes ``jsonschema/suite/gen_<class>_<file>_test.mbt``, embedding the
suite file verbatim (``#|`` raw lines, parsed at test time by
``@jsonschema.loads``, so numeric spellings survive) together with upstream
python-jsonschema's recorded outcome for each test (``suite_oracle.json``,
from ``suite_oracle.py``).

The remote documents (``remotes/``, served at ``http://localhost:1234/``)
are embedded in ``jsonschema/suite/gen_remotes_test.mbt``.

Usage:

    python3 jsonschema/scripts/gen_suite.py            # everything
    python3 jsonschema/scripts/gen_suite.py --formats-only
"""
import argparse
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from suite_config import SUITE, configs  # noqa: E402

OUT_DIR = os.path.join(HERE, "..", "suite")
ORACLE = os.path.join(HERE, "suite_oracle.json")


def raw_lines(text, indent):
    lines = text.rstrip("\n").split("\n")
    return "\n".join(f"{indent}#|{line}" for line in lines)


def sanitize(s):
    return re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_").lower()


def oracle_string(results):
    out = []
    for row in results:
        for outcome, reason in row:
            ch = outcome[0]
            out.append(ch.upper() if reason is not None else ch)
    return "".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--formats-only", action="store_true",
                        help="only generate optional/format groups (phase 1)")
    args = parser.parse_args()

    oracle = {}
    if os.path.exists(ORACLE):
        with open(ORACLE) as f:
            oracle = json.load(f)

    os.makedirs(OUT_DIR, exist_ok=True)
    for old in glob.glob(os.path.join(OUT_DIR, "gen_*_test.mbt")):
        os.remove(old)

    count = 0
    for cls_name, groups, _validator, use_format, _skip in configs():
        for version, rel in groups:
            if args.formats_only and not rel.startswith("optional/format/"):
                continue
            path = os.path.join(SUITE, "tests", version, rel)
            with open(path, encoding="utf-8") as f:
                text = f.read()
            key = f"{cls_name}|{version}/{rel}"
            upstream = oracle_string(oracle[key]) if key in oracle else ""
            name = f"gen_{sanitize(cls_name)}_{sanitize(version)}_{sanitize(rel[:-5])}_test.mbt"
            body = (
                "// Code generated by jsonschema/scripts/gen_suite.py. DO NOT EDIT.\n\n"
                "///|\n"
                f'test "{cls_name}: {version}/{rel}" {{\n'
                "  inspect(\n"
                "    run_suite_file(\n"
                f'      "{cls_name}",\n'
                f'      "{version}",\n'
                f'      "{rel}",\n'
                f"      format_checker={'true' if use_format else 'false'},\n"
                f'      upstream="{upstream}",\n'
                "      (\n"
                f"{raw_lines(text, '        ')}\n"
                "      ),\n"
                "    ),\n"
                '    content="",\n'
                "  )\n"
                "}\n"
            )
            with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8") as f:
                f.write(body)
            count += 1

    if not args.formats_only:
        remotes = []
        root = os.path.join(SUITE, "remotes")
        for path in sorted(glob.glob(os.path.join(root, "**", "*.json"),
                                     recursive=True)):
            rel = os.path.relpath(path, root).replace(os.sep, "/")
            with open(path, encoding="utf-8") as f:
                remotes.append((rel, f.read()))
        lines = [
            "// Code generated by jsonschema/scripts/gen_suite.py. DO NOT EDIT.",
            "",
            "///|",
            "/// The suite's `remotes/` documents: (path relative to `remotes/`,",
            "/// document text).",
            "let suite_remotes : Array[(String, String)] = [",
        ]
        for rel, text in remotes:
            lines.append("  (")
            lines.append(f'    "{rel}",')
            lines.append("    (")
            lines.append(raw_lines(text, "      "))
            lines.append("    ),")
            lines.append("  ),")
        lines.append("]")
        with open(os.path.join(OUT_DIR, "gen_remotes_test.mbt"), "w",
                  encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
    print(f"wrote {count} suite test files", file=sys.stderr)


if __name__ == "__main__":
    main()
