#!/usr/bin/env python3
"""
Generate specifications/schemas.mbt: every metaschema and vocabulary shipped
by ``jsonschema-specifications`` (``jsonschema_specifications/schemas/**``),
embedded verbatim and parsed lazily at runtime.

Usage:

    python3 jsonschema/scripts/gen_specifications.py [path/to/schemas]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = os.path.join(
    HERE, "..", "..", "upstream", "jsonschema-specifications",
    "jsonschema_specifications", "schemas",
)
OUT = os.path.join(HERE, "..", "specifications", "schemas.mbt")


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    entries = []
    # Same traversal as jsonschema_specifications._core._schemas (sorted, for
    # reproducibility).
    for version in sorted(os.listdir(root)):
        if version.startswith("."):
            continue
        vdir = os.path.join(root, version)
        for child in sorted(os.listdir(vdir)):
            cpath = os.path.join(vdir, child)
            paths = [cpath] if os.path.isfile(cpath) else [
                os.path.join(cpath, p) for p in sorted(os.listdir(cpath))
                if not p.startswith(".")
            ]
            for path in paths:
                with open(path, encoding="utf-8") as f:
                    text = f.read()
                contents = json.loads(text)
                uri = contents.get("$id", contents.get("id"))
                rel = os.path.relpath(path, root).replace(os.sep, "/")
                entries.append((uri, rel, text))
    lines = [
        "// Code generated by jsonschema/scripts/gen_specifications.py. DO NOT EDIT.",
        "",
        "///|",
        "/// `(id, path within jsonschema_specifications/schemas, text)` of each",
        "/// shipped schema.",
        "let schema_sources : Array[(String, String, String)] = [",
    ]
    for uri, rel, text in entries:
        lines.append("  (")
        lines.append(f"    {json.dumps(uri)},")
        lines.append(f"    {json.dumps(rel)},")
        lines.append("    (")
        for line in text.rstrip("\n").split("\n"):
            lines.append(f"      #|{line}")
        lines.append("    ),")
        lines.append("  ),")
    lines.append("]")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(entries)} schemas to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
