#!/usr/bin/env python3
"""
Generate internal/formats/data.mbt: data tables taken verbatim from the
third-party libraries python-jsonschema uses for format checking:

* the RFC 3986 / 3987 regular expressions of ``rfc3987`` (as Python regex
  source, interpreted by the port of ``re`` in internal/regex), and
* the CSS3 color names of ``webcolors``.

Usage (needs ``rfc3987`` and ``webcolors`` importable):

    python3 jsonschema/scripts/gen_format_data.py
"""
import importlib.metadata
import json
import os

import rfc3987
import webcolors
from webcolors import _definitions

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "internal", "formats", "data.mbt")


def lit(s):
    return json.dumps(s, ensure_ascii=True)


def main():
    pats = rfc3987.format_patterns()
    lines = [
        "// Code generated by jsonschema/scripts/gen_format_data.py. DO NOT EDIT.",
        f"// rfc3987 {rfc3987.__version__}; webcolors {importlib.metadata.version('webcolors')}.",
        "",
    ]
    for rule in ["URI", "URI_reference", "IRI", "IRI_reference"]:
        lines += [
            "///|",
            f"/// `rfc3987.format_patterns()[{rule!r}]` (Python `re` syntax).",
            f"let rfc3987_{rule.lower()}_pattern : String = {lit(pats[rule])}",
            "",
        ]
    names = sorted(_definitions._names_to_hex["css3"])
    lines += [
        "///|",
        "/// The CSS3 color names known to `webcolors.name_to_hex`.",
        "let css3_color_names : Array[String] = [",
    ]
    for n in names:
        lines.append(f"  {lit(n)},")
    lines += ["]", ""]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
